### ISSUE TITLE
humanize telephone numbers

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/Global-Studies#13]
i.e. 215-204-9999 rather than 2152049999. Could just add hyphens to phone numbers across faculty.yaml

**Comment by tu-chill** [comment]
dashes are cool. sometimes dots are even cooler. I looked at how the numbers are styled on liberalarts.temple.edu and -> (215) 204-7743 is already in use. We can talk with Zac and Zach if we feel strongly it should be dashes or dots

**Comment by tu-chill** [comment]
Dots! but this means we would need to edit phone numbers on liberalarts.temple.edu to be consistent.

**Comment by tu-chill** [comment]
let us see if we can git it to come out of Drupal with dots. Instead of having to make something with javascript.
