### ISSUE TITLE
media mentions and event links broken

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/Global-Studies#14]

**Comment by pixelyunicorn** [comment]
As of right now, the feed does not return full URLs, only relative URLs. Should I append http://liberalarts.temple.edu to each link or wait for the feed to return full URLs?

**Comment by tu-chill** [comment]
Drupal is a beast. I'd rather do it in the beast. but may have to set a condition on the non-drupal side of life as it may require code to be pushed from acquia dev to production.

**Comment by tu-chill** [comment]
feeds out of liberal-arts now send absolute paths for content and images
