### ISSUE TITLE
News story link - pulling in image caption

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Global-Studies#17]
Seems like if a news story has an image caption, it is pulling that in instead of the page title (see "Photo by Tanya Patra") and breaking the link to the story.

**Comment by tu-chill** [comment]
<img width="295" alt="screen shot 2017-01-18 at 12 37 35 pm" src="https://cloud.githubusercontent.com/assets/12816361/22075673/ece6aa5a-dd7a-11e6-9d13-d688ceffdcb7.png">


https://develop.cla.temple.edu/global-studies/

**Comment by tu-chill** [comment]
This card treatment is being phased out. The feed from Drupal needs to be better.
