### ISSUE TITLE
Universal header dropdown

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Global-Studies#18]
When you click the dropdown to all College programs, the arrow disappears and you cannot collapse the menu.

**Comment by tu-chill** [comment]
![screen shot 2017-01-18 at 12 31 29 pm](https://cloud.githubusercontent.com/assets/12816361/22075484/23c28036-dd7a-11e6-8141-4f096a84ff21.png)

For large screens, we've moved the College Mega Menu link to be in line with the University link. We can roll this back to the previous position and continue to work in the theme to work out the visual and interaction design for this College Mega Menu

![screen shot 2017-01-18 at 12 31 43 pm](https://cloud.githubusercontent.com/assets/12816361/22075486/255ed37c-dd7a-11e6-817c-f67c7fb9eb94.png)

I believe the link is under the mega menu by the amount that the link was moved toward the top of the document.

https://develop.cla.temple.edu/global-studies/

**Comment by tu-chill** [comment]
adding a request for cursor pointer finger action

**Comment by tu-chill** [comment]
This is High Priority. We will not launch until this is fixed.

**Comment by tu-chill** [comment]
This functions. I'm closing the issue. Issue was in the TUTheme commit https://github.com/TULiberalArts/TUtheme/commit/585c70198475df79931a37fc9e77d1955b0066eb
