### ISSUE TITLE
News and Media Mentions Widgets

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Global-Studies#19]
Drupal will provide JSON feed. 

- The first widget should list the last 4 or 5. 

- If there is only one, we can switch view it as a card.

- if there are no news or media mentions, we'll need some evergreen content to link to our press room.

#17 the old way

**Comment by tu-chill** [comment]
https://liberalarts.temple.edu/news/global-studies/rss
https://liberalarts.temple.edu/news/global-studies/json
https://liberalarts.temple.edu/news/global-studies/csv

**Comment by tu-chill** [comment]
changing to use csv until views yaml can get pushed on Liberal Arts

**Comment by tu-chill** [comment]
Added Zac to this issue. Want his input on how we will degrade gracefully

**Comment by tu-chill** [comment]
This is basically the same issue as events. What is the design for one news story? What is the design for when there are no stories?

**Comment by tu-chill** [comment]
Can you send Node id or path to missing articles. Also, we can sort my type so that news stories show first and if there are no articles than media mentions

**Comment by tu-chill** [comment]
I found this one - It was tagged with the NPD taxonomy but did not have a TLA program association. 
![screen shot 2017-02-22 at 1 37 21 pm](https://cloud.githubusercontent.com/assets/12816361/23226588/1353d8bc-f904-11e6-9f8e-ee1bacf6566f.png)
![screen shot 2017-02-22 at 1 37 08 pm](https://cloud.githubusercontent.com/assets/12816361/23226594/1adc5898-f904-11e6-8fd4-cbdefac036b2.png)


https://liberalarts.temple.edu/about-us/newsroom/temple-sociologist-questions-efficacy-measuring-school-climate


are there others?

**Comment by ZMcGroarty** [comment]
For unpopulated news/events lets create two black cards that can individually populate. 

See attachments for rough PS cut job.

![homepage_none](https://cloud.githubusercontent.com/assets/15017242/23228324/20fea98c-f90a-11e6-8d7e-b5ce166997a7.jpg)


![homepage_one](https://cloud.githubusercontent.com/assets/15017242/23228326/252d6a70-f90a-11e6-8594-28bcf8874a87.jpg)

**Comment by tu-chill** [comment]
@ZMcGroarty This is great! @LabLayers we can discuss what needs to come from drupal - if anything.
