### ISSUE TITLE
HeadShots Faculty

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Global-Studies#21]
The old faces stretch and pinch. Let us get the new headshots

**Comment by CVE82** [comment]
Okay great no problem, I will touch base with Zac today about OwlBox so I can get them =)

**Comment by tu-chill** [comment]
@ZMcGroarty in the Jekyll theme we were using squares. We can use 3X4 if that is what we want to do. The Headshots on in the owl box have a lot of headroom. I believe Chelsea started to crop them to 3X4.

**Comment by tu-chill** [comment]
Now I'm repeating myself. Sorry.

**Comment by ZMcGroarty** [comment]
Yeah 3x4 is good for me. Do you need me to do anything there?



On Wed, Feb 15, 2017 at 7:20 PM -0500, "Christopher Hill" <notifications@github.com<mailto:notifications@github.com>> wrote:


Now I'm repeating myself. Sorry.

**Comment by tu-chill** [comment]
It looks like the Profile Template can now handle square or 3X4
