### ISSUE TITLE
News story feed - pulling in wrong fields

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Global-Studies#22]
@tu-chill  most recent news story being pulled into GS still has "Photo by Tanya Patra" where the story title and link should be. I removed the image caption from the story in Drupal, but the issue persists. This should "Title" field, as it does for the rest of the stories.

**Comment by tu-chill** [comment]
The feed out of Drupal has been updated to send proper fields. The links are absolute. I'm serving it three ways RSS, JSON, and CSV. CSV seems to be the best for parsing with Jekyll.

liberalarts.temple.edu/news/global-studies/rss
liberalarts.temple.edu/news/global-studies/json
liberalarts.temple.edu/news/global-studies/csv

**Comment by tu-chill** [comment]
@LabLayers what is the status on consuming CSV? and do we need to look into a cronjob to check for new articles? @lpaglia could you help with the cronjob?

**Comment by tu-chill** [comment]
Closing this issue and making new issue for cronjob
