### ISSUE TITLE
Ready to pull the trigger by 3pm, last three tasks to be completed

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Global-Studies#23]
Hello! So we would like to have this site live by 3pm there are just three things that need to be completed.

**Victor: 

1) Please link three text boxes on homepage
 2) Please make the fist box the same size as the other two.**

**Zac M.: Please insert a hero image when possible. We will go live without it and can add it when ready.** 

Lido- Can you flip the switch at 3pm please? 

Thank you all!

**Comment by pixelyunicorn** [comment]
Once this travis build happens it is ready to go live. No hero image yet, but the 2 remaining issues have been resolved for now.

**Comment by CVE82** [comment]
Thank you so much! It is already live Lido cc'd you in the email with the url earlier.
