### ISSUE TITLE
Parse Feed to bring in current faculty data from Drupal

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Global-Studies#24]
Hey Victor,

Can you please work on this as well so we can get the current profile pictures to feed form Drupal? Thanks you!

**Comment by pixelyunicorn** [comment]
I need the URL for the faculty feed (csv)

**Comment by tu-chill** [comment]
@camille i changed the wording on this issue.

@victor 
liberal arts.temple.edu/profiles/global-studies/cvs

**Comment by tu-chill** [comment]
Also Drupal images are rectangles and TU theme has been using squares. Currently we are stretching faces. 

@zac it's is your call for visual design.

**Comment by ZMcGroarty** [comment]
I believe Chelsea cropped them all to squares (in the owl box) if that's what we need.



On Wed, Feb 15, 2017 at 7:18 PM -0500, "Christopher Hill" <notifications@github.com<mailto:notifications@github.com>> wrote:


Also Drupal images are rectangles and TU theme has been using squares. Currently we are stretching faces.

@zac<https://github.com/zac> it's is your call for visual design.

**Comment by CVE82** [comment]
I just got home, noticed you changed the title already, thanks!

**Comment by CVE82** [comment]
Not all of the faculty profiles are cropped, just a small batch. Believe it's a work in progress... The ones that are cropped have been added and or swapped out.

**Comment by tu-chill** [comment]
working as expected. for now
