### ISSUE TITLE
Mark Pollack listed twice on faculty page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Global-Studies#26]
Hey, I just noticed that Mark Pollack is listed twice on the page, he should only appear as the first faculty member. Thanks!

**Comment by tu-chill** [comment]
Mark has 2 TLA Faculty Profiles. Not sure which one to keep. Node 14521 created on Feb 14 is most likely the most up to date. If possible, I'd like update Node 13221 and remove Node 14521. URL for 14521 ends with a -0 and doesn't have the full revision history dating back to 2016-10-19 16:53:40 -0400k

![screen shot 2017-02-17 at 7 12 35 am](https://cloud.githubusercontent.com/assets/12816361/23064891/a81ba858-f4e0-11e6-9acd-b2c217bff9a0.png)

After the node is removed, a build on the Global Studies repo will need to be initiated.

**Comment by CVE82** [comment]
Roger that!



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by CVE82** [comment]
First Mark deleted. Will initiate build.
