### ISSUE TITLE
Create New Build for faculty content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Global-Studies#27]
Hey Victor, 

When you are back from DC can you fix the build we were talking about earlier? Thanks! =D

**Comment by pixelyunicorn** [comment]
I'm having a issue building the site, because htmlproofer will fail it if a headshot is not found (see https://liberalarts.temple.edu/sites/liberalarts/files/Pollack%20-%20Photo.jpg)

**Comment by pixelyunicorn** [comment]
Can you make sure that all faculty in drupal have a headshot that lead to a valid image, and if they don't then can you upload (or fall back to) a placeholder in drupal? That seems to work best for now.

**Comment by CVE82** [comment]
Yes, all the images that are in Drupal are coming right from the WordPress media library or from the current faculty profile folder. I am not sure how to upload/create a placeholder to insert.

**Comment by tu-chill** [comment]
Assign this to me. I'll look at it when I can.

C.Hill
Marketing Technology
College of Liberal Arts
Temple University

On Feb 20, 2017, at 1:31 PM, Camille Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, all the images that are in Drupal are coming right from the WordPress media library or from the current faculty profile folder. I am not sure how to upload/create a placeholder to insert.

-

**Comment by pixelyunicorn** [comment]
Nevermind, got this build working.

**Comment by pixelyunicorn** [comment]
However, Mark A. Pollack no longer appears as the first entry inside the faculty csv file.

**Comment by pixelyunicorn** [comment]
Moved it up manually. Closing, since #28 was created to address placeholder image.
