### ISSUE TITLE
Placeholder for faculty profiles

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Global-Studies#28]
WC, can you show me how to create a grey box placeholder for faculty that have no images, upon your return? Thank you!

**Comment by tu-chill** [comment]
![no_picture](https://cloud.githubusercontent.com/assets/12816361/23322513/52e577e2-fab2-11e6-943c-406b8c27bd1d.png)

set as default image in drupal for headshot field in TLA Profiles Content Type
