### ISSUE TITLE
Hero Image Testing

### ISSUE THREAD

**Issue by ZMcGroarty** [TULiberalArts/Global-Studies#29]
Lets try to use a hero image on Global Studies.

See attached, let me know if it needs to be rescaled. Fades to #a41e35 on each side.

Convert "Exploring The World" H1 and subtext to white and sit on top of hero as seen below.

![hero_globalstudies](https://cloud.githubusercontent.com/assets/15017242/23228530/d3041ac2-f90a-11e6-8a66-f64d7f8fbce0.png)

Mock:

![homepage_mock](https://cloud.githubusercontent.com/assets/15017242/23228535/d873ff0e-f90a-11e6-9087-49ba024d05d9.jpg)

**Comment by pixelyunicorn** [comment]
Sure, I can work on making it happen.

**Comment by pixelyunicorn** [comment]
Implemented, let me know what you think @ZMcGroarty

**Comment by ZMcGroarty** [comment]
Would it be on develop or live? not seeing it on either yet. Though the columns on some internal pages (Faculty, Undergraduate) is now going full width and wacky.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Feb 24, 2017, at 2:29 PM, Victor Lourng <notifications@github.com<mailto:notifications@github.com>> wrote:


Implemented, let me know what you think @ZMcGroarty<https://github.com/ZMcGroarty>

**Comment by pixelyunicorn** [comment]
@ZMcGroarty should be live at http://develop.cla.temple.edu/global-studies/ (I'm working on whacky columns right now, just changed the grid system)

**Comment by ZMcGroarty** [comment]
Ah, there it goes!

Hero looks great. Just a side note, I opened in safari too, and the nav all left aligns. Though I just might have a really old version of safari. Chrome looks good.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Feb 24, 2017, at 2:32 PM, Victor Lourng <notifications@github.com<mailto:notifications@github.com>> wrote:


@ZMcGroarty<https://github.com/ZMcGroarty> should be live at http://develop.cla.temple.edu/global-studies/ (I'm working on whacky columns right now, just changed the grid system)

**Comment by pixelyunicorn** [comment]
Give it a few minutes, I fixed it. The nav left aligns only on smaller windows or if they do not support flexbox.

**Comment by pixelyunicorn** [comment]
If you aren't seeing the changes, press command+shift+r to trigger a hard reload

**Comment by pixelyunicorn** [comment]
@lidopaglia can we disable the cache header for develop sites?

**Comment by tu-chill** [comment]
@ZMcGroarty and @LabLayers looks great
