### ISSUE TITLE
Remove background images in promotion table

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Global-Studies#30]
#29 added a visual element to the top of entrance page.

@ZMcGroarty and @LabLayers  I suggest we remove the background images in the cards in the Promotion Table

<img width="1341" alt="screen shot 2017-02-24 at 5 02 58 pm" src="https://cloud.githubusercontent.com/assets/12816361/23322699/241a1c5a-fab3-11e6-9441-1060e4b27b0f.png">

**Comment by ZMcGroarty** [comment]
Is this too much? Not sure of the compatability issues:

On **.overlay-unit** disable background color and add
`background:-webkit-linear-gradient(top, #a41e35 29%,#fcb426 100%)`

I can tweak colors for different majors eventually, but not all the colors play nice together. The red/yellow has been our micro brand in CLA though.

![screen shot 2017-03-02 at 2 41 57 pm](https://cloud.githubusercontent.com/assets/15017242/23523948/c205fefa-ff56-11e6-9289-1029f48f6d0e.png)

**Comment by tu-chill** [comment]
It has a mad max A World Without Temple and fire and brimstone.


On Mar 2, 2017, at 2:44 PM, Zachary McGroarty <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this too much? Not sure of the compatability issues:

On .overlay-unit disable background color and add
background:-webkit-linear-gradient(top, #a41e35 29%,#fcb426 100%)

I can tweak colors for different majors eventually, but not all the colors play nice together. The red/yellow has been our micro brand in CLA though.

[screen shot 2017-03-02 at 2 41 57 pm]<https://cloud.githubusercontent.com/assets/15017242/23523948/c205fefa-ff56-11e6-9289-1029f48f6d0e.png>

**Comment by ZMcGroarty** [comment]
Swap that 100% to 175% and its a lot more subtle, we can play with those numbers between and above 175.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Mar 2, 2017, at 2:49 PM, Christopher Hill <notifications@github.com<mailto:notifications@github.com>> wrote:

It has a mad max A World Without Temple and fire and brimstone.


On Mar 2, 2017, at 2:44 PM, Zachary McGroarty <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Is this too much? Not sure of the compatability issues:

On .overlay-unit disable background color and add
background:-webkit-linear-gradient(top, #a41e35 29%,#fcb426 100%)

I can tweak colors for different majors eventually, but not all the colors play nice together. The red/yellow has been our micro brand in CLA though.

[screen shot 2017-03-02 at 2 41 57 pm]<https://cloud.githubusercontent.com/assets/15017242/23523948/c205fefa-ff56-11e6-9289-1029f48f6d0e.png>

**Comment by tu-chill** [comment]
I do like the direction. I actually like the thunderdome movie. and if it keep with our other digital branding then we can test it out.


On Mar 2, 2017, at 2:53 PM, Zachary McGroarty <notifications@github.com<mailto:notifications@github.com>> wrote:

Swap that 100% to 175% and its a lot more subtle, we can play with those numbers between and above 175.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu><mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu><http://liberalarts.temple.edu>





On Mar 2, 2017, at 2:49 PM, Christopher Hill <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

It has a mad max A World Without Temple and fire and brimstone.


On Mar 2, 2017, at 2:44 PM, Zachary McGroarty <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Is this too much? Not sure of the compatability issues:

On .overlay-unit disable background color and add
background:-webkit-linear-gradient(top, #a41e35 29%,#fcb426 100%)

I can tweak colors for different majors eventually, but not all the colors play nice together. The red/yellow has been our micro brand in CLA though.

[screen shot 2017-03-02 at 2 41 57 pm]<https://cloud.githubusercontent.com/assets/15017242/23523948/c205fefa-ff56-11e6-9289-1029f48f6d0e.png>

**Comment by ZMcGroarty** [comment]
Another nice one:

background:-webkit-linear-gradient(top, #a41e35 29%,#007bc2 200%)

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Mar 2, 2017, at 2:55 PM, Christopher Hill <notifications@github.com<mailto:notifications@github.com>> wrote:

I do like the direction. I actually like the thunderdome movie. and if it keep with our other digital branding then we can test it out.


On Mar 2, 2017, at 2:53 PM, Zachary McGroarty <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Swap that 100% to 175% and its a lot more subtle, we can play with those numbers between and above 175.

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu><mailto:zachary.mcgroarty@temple.edu><mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu><http://liberalarts.temple.edu><http://liberalarts.temple.edu>





On Mar 2, 2017, at 2:49 PM, Christopher Hill <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

It has a mad max A World Without Temple and fire and brimstone.


On Mar 2, 2017, at 2:44 PM, Zachary McGroarty <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Is this too much? Not sure of the compatability issues:

On .overlay-unit disable background color and add
background:-webkit-linear-gradient(top, #a41e35 29%,#fcb426 100%)

I can tweak colors for different majors eventually, but not all the colors play nice together. The red/yellow has been our micro brand in CLA though.

[screen shot 2017-03-02 at 2 41 57 pm]<https://cloud.githubusercontent.com/assets/15017242/23523948/c205fefa-ff56-11e6-9289-1029f48f6d0e.png>

**Comment by tu-chill** [comment]
Images are not being included. We have not implemented the fade. We should create a new issue for a theme enhancement requesting alt card styles.
