### ISSUE TITLE
entrance page | Hero Image

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Global-Studies#8]
I can see using the page-feature as it has been developed. There will also be a time when a program does not have a page feature. In the case of no page feature, I'd like to see a fluid 130-pixel band under the primary nav and before the main content on the page.

**Comment by tu-chill** [comment]
not having the band - are we sure that Global Studies doesn't have some content that we could place in the hero feature? The functionality exists. I will bring this up during meeting on Thursday 1/19

**Comment by tu-chill** [comment]
closing this issue unresolved. Global Studies is launching without an image on front page.

**Comment by pixelyunicorn** [comment]
The theme supports hero images, it's just not implemented (as of now) in any of our sites.
